services:
  db:
    image: mysql:8
    container_name: CadastroEmpresaDB
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=adm1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
